# Generated by Django 2.2.24 on 2022-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/profile/default.png', upload_to='profile'),
        ),
    ]
