# Generated by Django 2.2.24 on 2022-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0004_auto_20220107_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='codesphere/profile/default.png', upload_to='profile/'),
        ),
    ]
