# Generated by Django 2.2.24 on 2022-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0005_auto_20220107_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
