# Generated by Django 2.2.24 on 2022-01-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0006_auto_20220107_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
