# Generated by Django 2.2.24 on 2022-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0007_remove_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
