# Generated by Django 2.2.24 on 2022-02-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0011_auto_20220207_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.TextField(default='/media/profile/default.png'),
        ),
    ]
