# Generated by Django 2.2.24 on 2022-02-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0012_auto_20220207_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
