# Generated by Django 2.2.24 on 2022-02-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0016_auto_20220210_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
