# Generated by Django 2.2.24 on 2022-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0017_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('question', models.ManyToManyField(blank=True, related_name='colletive_question', to='codesphere.Question')),
            ],
        ),
    ]
