# Generated by Django 2.2.24 on 2022-02-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0018_collective'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='icon',
            field=models.TextField(default='/media/collective/default.png'),
        ),
    ]
