# Generated by Django 2.2.24 on 2022-02-21 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesphere', '0019_collective_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collective_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
